name: Fuel Price Check

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */2 * * *"

permissions:
  contents: write

jobs:
  check-fuel-price:
    runs-on: ubuntu-latest

    steps:

      - name: Download repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check fuel price
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python fuel_alert.py

      - name: Save price history
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add fuel_data.json

          git diff --cached --quiet || git commit -m "Update fuel price"

          git push
